// apps/next/components/ProgressBar.tsx
import { useState, useEffect } from 'react'
import { EventEmitter } from 'events'
import { motion } from 'framer-motion'
import Header from './Header'
import Content from './Content'
import Section from './Section'

function useProgress (max: number, emitter: EventEmitter) {
  const [value, setValue] = useState(0)

  useEffect(() => {
    function onUpdate (value: number) {
      setValue(Number(((value / max) * 100).toFixed(0)))
    }
    emitter.addListener('update', onUpdate)
    return () => {
      emitter.removeListener('update', onUpdate)
    }
  }, [])

  return value
}

function FixedProgressView ({ progress }: { progress: number }) {
  if (progress < 10) {
    return (
      <span>
        <span
          style={{
            visibility: 'hidden',
          }}
        >
          00
        </span>
        {progress}
      </span>
    )
  }
  if (progress < 100) {
    return (
      <span>
        <span
          style={{
            visibility: 'hidden',
          }}
        >
          0
        </span>
        {progress}
      </span>
    )
  }
  return <>100</>
}

function ProgressBar () {
  const emitter = new EventEmitter()
  const progress = useProgress(100, emitter)

  useEffect(() => {
    let count = 0
    const interval = setInterval(() => {
      count += Math.floor(Math.random() * 20)
      if (count > 100) {
        count = 100
        clearInterval(interval)
      }
      emitter.emit('update', count)
    }, 1000)
    return () => clearInterval(interval)
  }, [])

  let color = 'rgb(137, 242, 152)'
  if (progress <= 25) {
    color = 'rgb(237, 103, 94)'
  } else if (progress <= 50) {
    color = 'rgb(244, 248, 168)'
  }

  return (
    <Content>
      <Header />
      <Section>
        <div className="flex items-center">
          <div className="h-5 w-96 mr-3">
            <motion.div
              className="h-full w-0"
              animate={{
                backgroundColor: color,
                width: progress + '%',
              }}
              transition={{ duration: 0.4 }}
            />
          </div>
          <div>
            <FixedProgressView progress={progress} />%
          </div>
        </div>
      </Section>
    </Content>
  )
}

export default ProgressBar

// apps/svelte/src/routes/progress-bar/+page.svelte
<script lang="ts">
	import { onDestroy } from "svelte"
	import { tweened } from "svelte/motion"
	import { quadOut } from "svelte/easing"

	let percentage = 0
	const progress = tweened(0, {
		duration: 600,
		easing: quadOut,
	})

	const interval = setInterval(() => {
		percentage = percentage + Math.max(5, Math.floor(Math.random() * 20))
		if (percentage >= 100) {
			percentage = 100
			clearInterval(interval)
		}
		progress.set(percentage)
	}, 1000)

	onDestroy(() => {
		clearInterval(interval)
	})
</script>

<svelte:head>
	<title>Progress Bar | emiljohansson.dev</title>
	<meta name="description" content="Progress bar" />
</svelte:head>

<header class="bg-white border-b border-slate-200 px-6 py-12">
	<h1>Progress Bar</h1>
</header>

<main>
	<div class="flex items-center">
		<div
			aria-valuemax={100}
			aria-valuemin={0}
			aria-valuenow={100}
			aria-valuetext="100%"
			role="progressbar"
			data-state="complete"
			data-value="100"
			data-max="100"
			class="relative overflow-hidden bg-black-rich/50 rounded-full w-96 h-6"
			title="Progress"
		>
			<div
				class="h-full w-0 bg-green-400"
				class:bg-red-400={$progress <= 25}
				class:bg-yellow-200={$progress > 25 && $progress <= 50}
				data-state="complete"
				data-value="100"
				data-max="100"
				style="width: {$progress}%;"
			/>
		</div>
		<div class="ml-2">
			{percentage}%
		</div>
	</div>
</main>
