// apps/next/pages/current-time.tsx
import Head from 'next/head'
import useCurrentTime from 'lib/hooks/useCurrentTime'
import Layout from '@/components/Layout'
import Header from '@/components/Header'
import Content from '@/components/Content'
import Section from '@/components/Section'

const CurrentTimePage = () => {
  const { hours, minutes, meridiem } = useCurrentTime()

  return (
    <Layout>
      <Head>
        <title>Current Time</title>
        <meta name="description" content="Current Time" />
      </Head>
      <Content>
        <Header />
        <Section size="large">
          <style jsx>{`
            .meridiem {
              margin-bottom: -18px;
            }
          `}</style>

          {hours}:{minutes}
          <span className="text-3/6 meridiem">{meridiem}</span>
        </Section>
      </Content>
    </Layout>
  )
}

export default CurrentTimePage

// apps/svelte/src/routes/current-time/+page.svelte
<script lang="ts">
	import { onDestroy } from "svelte"
	import { getCurrentTime } from "lib/utils/date"

	let { hours, minutes, meridiem } = getCurrentTime()

	const interval = setInterval(() => {
		const newTime = getCurrentTime()
		minutes = newTime.minutes
		hours = newTime.hours
		meridiem = newTime.meridiem
	}, 1000)

	onDestroy(() => {
		clearInterval(interval)
	})
</script>

<svelte:head>
	<title>Current Time | emiljohansson.dev</title>
	<meta name="description" content="Genrates a random string" />
</svelte:head>

<header class="bg-white border-b border-slate-200 px-6 py-12">
	<h1>Current Time</h1>
</header>

<main>
	{hours}:{minutes}
	<span class="text-3/6 meridiem">{meridiem}</span>
</main>

<style>
	.meridiem {
		margin-bottom: -18px;
	}
</style>
