// apps/svelte/src/routes/random-string/+page.svelte
<script lang="ts">
	import type { PageData } from "./$types"
	// import randomString from "@emiljohansson/random-string"

	export let data: PageData

	let value = data.value
</script>

<svelte:head>
	<title>Random String | emiljohansson.dev</title>
	<meta name="description" content="Genrates a random string" />
</svelte:head>

<header class="bg-white border-b border-slate-200 px-6 py-12">
	<h1>Random string</h1>
</header>

<main>
	{value}
</main>

// pages/random-string.tsx
import Head from 'next/head'
import randomString from '@emiljohansson/random-string'
import Layout from '../components/Layout'
import RandomString from '../components/RandomString'

export async function getServerSideProps() {
  return {
    props: {
      value: randomString()
    }
  }
}

const SecondPage = ({ value }) => {
  return (
    <Layout>
      <Head>
        <title>Random String</title>
        <meta name="description" content="Genrates a random string" />
      </Head>
      <RandomString
        initialValue={value}
      />
    </Layout>
  )
}

export default SecondPage
