// apps/next/pages/calculate.tsx
import Head from 'next/head'
import { FormEvent, useState } from 'react'
import Content from '@/components/Content'
import Layout from '@/components/Layout'
import Section from '@/components/Section'
import Header from '@/components/Header'

const Calculate = () => {
  const [sum, setSum] = useState(0)

  const calculate = async (event: FormEvent<HTMLFormElement>) => {
    const form = event.currentTarget
    const formElements = form.elements as typeof form.elements & {
      q: {
        value: string
      }
    }

    event.preventDefault()

    const res = await fetch('/api/calculate', {
      body: JSON.stringify({
        q: formElements.q.value,
      }),
      headers: {
        'Content-Type': 'application/json',
      },
      method: 'POST',
    })

    const result = await res.json()
    setSum(result.sum)
  }

  return (
    <Layout>
      <Head>
        <title>Calculate</title>
        <meta name="description" content="Calculate" />
      </Head>
      <Content>
        <Header />
        <Section size="normal">
          <h1 className="sr-only">Calculate</h1>
          <form onSubmit={calculate} action="/api/calculate" method="post">
            <input className="input" type="text" name="q" aria-label="Query" /><span className="ml-3" data-test="sum">{sum}</span>
            <button className="btn-primary mt-3 block" data-test="submit">Calculate</button>
          </form>
        </Section>
      </Content>
    </Layout>
  )
}

export default Calculate

// apps/svelte/src/routes/calculate/+page.svelte
<script lang="ts">
	import type { ActionData } from "./$types"
	import { enhance } from "$app/forms"

	export let form: ActionData
</script>

<svelte:head>
	<title>Calculator | emiljohansson.dev</title>
	<meta name="description" content="Genrates a Calculator" />
</svelte:head>

<header class="bg-white border-b border-slate-200 px-6 py-12">
	<h1>Calculator</h1>
</header>

<main>
	<form
		method="POST"
		use:enhance={() => {
			return async ({ update }) => {
				await update({ reset: false })
			}
		}}
	>
		<div class="flex items-center gap-2 mb-2">
			<!-- svelte-ignore a11y-autofocus -->
			<input
				class="input"
				type="text"
				name="query"
				aria-label="Query"
				autofocus
				placeholder="1+2"
			/>
			<span class="text-xl">= {form?.sum ?? "0"}</span>
		</div>
		<button class="btn-primary w-auto">Calculate</button>
	</form>
</main>
